# Generated by Django 4.2.3 on 2023-08-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0005_blogcomment_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
