# Generated by Django 4.2.3 on 2023-08-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0008_postmodel_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='categoryName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
