# Generated by Django 4.2.3 on 2024-01-31 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
        ('Blog_app', '0009_alter_categorymodel_categoryname'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.userprofilemodel'),
        ),
    ]
