# Generated by Django 4.2.3 on 2024-12-30 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0013_subscriptionmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='author',
        ),
    ]
