# Generated by Django 4.2.3 on 2024-12-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0016_alter_postmodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='status',
            field=models.CharField(choices=[('0', 'Draft'), ('1', 'Publish')], default='0', max_length=100),
        ),
    ]
